language: java

matrix:
  include:
    - os: osx
      osx_image: xcode9.3  # with JDK1.8.0_112-b16 installed
      name: osx-oraclejdk8

    - os: osx
      name: osx-go
      language: go
      go:
        - 1.10.x
      install:
        - export GOPATH="$GOPATH:$TRAVIS_BUILD_DIR/tsfile-go"
        - go get -v github.com/golang/snappy
      script: go test -v tsfile

    - os: linux
      name: linux-go
      language: go
      go:
        - 1.10.x
      install:
        - export GOPATH="$GOPATH:$TRAVIS_BUILD_DIR/tsfile-go"
        - go get -v github.com/golang/snappy
      script: go test -v tsfile

#    - os: windows
#      name: windows-go
#      language: go
#      go:
#        - 1.10.x
#      install:
#        - export GOPATH="$GOPATH:$TRAVIS_BUILD_DIR/tsfile-go"
#        - go get -v github.com/golang/snappy
#      script: go test -v tsfile

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
# skip `before_install` stage
before_install: true

# skip `install` stage
install: true

script:
  - java -version
#  - mvn apache-rat:check
  - mvn clean integration-test

after_success:
