matrix:
  include:
    - os: linux
      name: linux-go
      dist: trusty
      sudo: required
      before_install:
        - wget https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz -O jdk11.tar.gz
        - tar -xzf jdk11.tar.gz
      before_script:
        - export JAVA_HOME=$PWD/jdk-11.0.2/
        - export PATH=$JAVA_HOME/bin:$PATH
      script:
        - java -version
        - mvn clean integration-test
    - os: linux
      name: linux-openjdk8
      dist: trusty
      jdk: openjdk8
    - os: linux
      name: linux-oraclejdk8
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      name: linux-oraclejdk11
      dist: trusty
      jdk: oraclejdk11

language: go
 
go:
  - 1.9
 
sudo: required
 
install:
  - export GOPATH=$HOME/gopath/src/github.com/owenliang/bigpipe
  - export PATH=$PATH:$HOME/gopath/src/github.com/owenliang/bigpipe/bin/
  - go get -v github.com/Masterminds/glide
  - cd src/github.com/Masterminds/glide && go install && cd -
  - wget https://github.com/edenhill/librdkafka/archive/v0.9.5.tar.gz && tar -zxvf v0.9.5.tar.gz && cd librdkafka-0.9.5 && ./configure && make && sudo make install && cd -
  - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
 
script:
  - sh build.sh