matrix:
  include:
    - os: linux
      name: linux-go
      language: go
      go:
        - tip
      install:
        - export GOPATH=$HOME/gopath/zyccld/tsfile_go
        - go get -v github.com/golang/snappy
      script: go build tsfile